Bump to 7257135
radiorabe/centos-rpm-fdk-aac-dabplus-odr pull request #6
Opened 2017-02-17 11:19 UTC by hairmare

Bumps to the changes from https://github.com/Opendigitalradio/fdk-aac/pull/21 in our RPMs.

2017-02-17 12:59 UTC, paraenggu requested changes
Looks good, please add a changelog entry and update the year in the header copyright line. Afterwards this PR is good to go.

2017-02-17 13:29 UTC, hairmare commented
:expressionless:

Some day I'll hook this up in obs to automate it. The "everything is in scm and we still use manual changelogs" business is driving me nuts.

2017-02-17 14:06 UTC, paraenggu submitted a review, later dismissed
Could you please also adapt the copyright header to reflect the new year? https://github.com/radiorabe/centos-rpm-fdk-aac-dabplus-odr/blob/master/fdk-aac-dabplus-odr.spec#L4

2017-02-17 15:23 UTC, paraenggu commented
> Wasting a commit on some spaces makes as much sense as the parent -_-

feel free to squash them together, which would probably make sense here anyway.

2017-02-17 15:30 UTC, hairmare commented
Try squashing them thru the UI? I've never seen that happen 🔨

2017-02-17 16:32 UTC, paraenggu commented
> Try squashing them thru the UI?

there's a tool called `git` ;-)

2017-02-17 18:50 UTC, hairmare commented
> there's a tool called git ;-)

And there's nitpickery at a level that made me a bit tired 😉

2017-02-19 09:28 UTC, hairmare commented
squashed

2017-02-19 09:59 UTC, merged

2017-02-19 10:00 UTC, paraenggu commented
Thanks!